version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: order-service-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: order_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    build: ./order-service
    container_name: order-service-api
    restart: always
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DB_URL=postgres://admin:admin@db:5432/order_db?sslmode=disable
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - CONSUL_ADDRESS=consul:8500
    depends_on:
      - db
      - rabbitmq
      - consul

  kitchen-api:
    build: ./kitchen-service
    container_name: kitchen-service-api
    restart: always
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - DB_URL=postgres://admin:admin@db:5432/kitchen_db?sslmode=disable
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - CONSUL_ADDRESS=consul:8500
      - SERVICE_ADDRESS=kitchen-api
    depends_on:
      - db
      - rabbitmq
      - consul
    command: ["./api"]

  kitchen-worker:
    build: ./kitchen-service
    container_name: kitchen-service-worker
    restart: always
    environment:
      - PORT=3001
      - DB_URL=postgres://admin:admin@db:5432/kitchen_db?sslmode=disable
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - db
      - rabbitmq
    command: ["./worker"]

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  consul:
    image: hashicorp/consul:latest
    container_name: consul
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    command: "agent -dev -client=0.0.0.0"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3002:3000" # เข้าผ่าน Port 3002 (User/Pass: admin/admin)
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./promtail-config.yaml:/etc/promtail/config.yaml
    command: -config.file=/etc/promtail/config.yaml

  auth-service:
    build: ./auth-service
    container_name: auth-service-api
    restart: always
    ports:
      - "3005:3002"
    environment:
      - PORT=3002
      - DB_URL=postgres://admin:admin@db:5432/auth_db?sslmode=disable
      - PRIVATE_KEY_PATH=/app/private_key.pem
    volumes:
      - ./private_key.pem:/app/private_key.pem
    depends_on:
      - db

  gateway:
    image: krakend:latest
    container_name: api-gateway
    volumes:
      - ./krakend.json:/etc/krakend/krakend.json
      - ./public_key.pem:/etc/krakend/public_key.pem
      - ./public_key.json:/etc/krakend/public_key.json
    ports:
      - "8080:8080"
      - "9091:9091"
    depends_on:
      - api
      - kitchen-api
      - auth-service

  krakend-designer:
    image: devopsfaith/krakendesigner:latest
    container_name: krakend-designer
    ports:
      - "8787:80"

volumes:
  postgres_data:
