version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: order-service-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: order_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: ./order-service
    container_name: order-service-api
    restart: always
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DB_URL=postgres://admin:admin@db:5432/order_db?sslmode=disable
    depends_on:
      - db
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  postgres_data:


