DROP DATABASE IF EXISTS order_db;
DROP DATABASE IF EXISTS kitchen_db;
DROP DATABASE IF EXISTS auth_db;
DROP DATABASE IF EXISTS catalog_db;
DROP DATABASE IF EXISTS inventory_db;

CREATE DATABASE order_db;
CREATE DATABASE kitchen_db;
CREATE DATABASE auth_db;
CREATE DATABASE catalog_db;
CREATE DATABASE inventory_db;
